### ISSUE TITLE
Error when upgrading/removing/purging on ubuntu

### ISSUE THREAD

**Issue by MeltedLux** [MediaBrowser/Emby.Build#25]
Get:1 http://download.opensuse.org/repositories/home:/emby/xUbuntu_15.04/  emby-server 3.0.5781.1 [13.5 MB]
Fetched 13.5 MB in 0s (19.0 MB/s)
Preconfiguring packages ...
(Reading database ... 86418 files and directories currently installed.)
Preparing to unpack .../emby-server_3.0.5781.1_all.deb ...
/var/lib/dpkg/info/emby-server.prerm: 23: [: missing ]
/var/lib/dpkg/info/emby-server.prerm: 23: [: missing ]
Unpacking emby-server (3.0.5781.1) over (3.0.5781.0) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (225-1ubuntu9) ...
Setting up emby-server (3.0.5781.1) ...

Happens on 14.04/14.10/15.04/15.10 at minimum.

**Comment by hurricanehrndz** [comment]
Thank you. I believe those errors have been addressed in our beta and dev packages, stable will be updated after some testing periods. If you could test our beta package and please report back that would be greatly appreciated. Again Thank you for your feedback.

**Comment by MeltedLux** [comment]
Looks like it has been addressed in dev at least. Closing issue.
