### ISSUE TITLE
Update.sh broken

### ISSUE THREAD

**Issue by Gibby** [MediaBrowser/Emby.Build#26]
After installing a new container and then running Update.sh, the following error is produced:

Configuration file '/etc/sudoers.d/emby'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** emby (Y/I/N/O/D/Z) [default=N] ? D
WARNING: terminal is not fully functional
--- /etc/sudoers.d/emby 2015-09-22 12:00:47.000000000 -0400
+++ /etc/sudoers.d/emby.dpkg-new        2015-12-02 15:49:27.000000000 -0500
@@ -1,7 +1,7 @@
 #Allow emby to start, stop and restart itself
-nobody ALL=(ALL) NOPASSWD: /usr/bin/sv *
+emby ALL=(ALL) NOPASSWD: /usr/sbin/service emby-server *
 #Allow the server to mount iso images
-nobody ALL=(ALL) NOPASSWD: /bin/mount
-nobody ALL=(ALL) NOPASSWD: /bin/umount
+emby ALL=(ALL) NOPASSWD: /bin/mount
+emby ALL=(ALL) NOPASSWD: /bin/umount

-Defaults:nobody !requiretty
+Defaults:emby !requiretty
(END)

I think instead of messing with /etc/sudoers.d/emby when install.sh is ran, change the file to /etc/sudoers.d/emby.docker or something.

**Comment by Gibby** [comment]
After looking at sudoers manual, looks like it would have to be emby-docker since anything that has a . in it will be ignored in the sudoers.d directory.

**Comment by hurricanehrndz** [comment]
Thanks. I will ensure update gets fixed in the future releases.

**Comment by hurricanehrndz** [comment]
This has been fixed.
