### ISSUE TITLE
rockstor plugin rock-on json invalid

### ISSUE THREAD

**Issue by phillxnet** [MediaBrowser/Emby.Build#38]
When testing the Rockstor rock-on (plugin) app file embyserver.json in JSONLint:-
http://jsonlint.com/ it was found to be invalid. This was also confirmed in Rockstor's own logs:-
/opt/rockstor/var/log/rockstor.log
Looks like it's just missing a closing bracket for this problem.
I am in the process of submitting a pull request to address this.

**Comment by hurricanehrndz** [comment]
Thanks. I will look into it.
