### ISSUE TITLE
Cannot Start Container Error

### ISSUE THREAD

**Issue by Tdunk18** [MediaBrowser/Emby.Build#50]
Error response from daemon: Cannot start container c9b993897aef9a6b48e1b18d9ee0e9a71e41b13e6cfcbac43823cf04bc7ddaec: [8] System error: exec format error
root@Storage root #

**Comment by hurricanehrndz** [comment]
Any more updates on this?

**Comment by anderbytes** [comment]
Are you sure it isn't a problem of your Docker installation? Here the image runs smoothly

**Comment by hurricanehrndz** [comment]
Closing since there hasn't been any response.
