### ISSUE TITLE
Provide access to hardware acceleration in docker container

### ISSUE THREAD

**Issue by hurricanehrndz** [MediaBrowser/Emby.Build#54]
The emby container could benefit from a performance boost by enabling hardware acceleration with the current docker containers. For this to be achieved `/dev/dri`  needs to be mapped by the wrapper script. Additionally, the supporting libraries on the system need to match the ones available within the container. This endeavor is practically impossible.

There seems to be work being done to some how reuse the libraries already available on the host. The following GitHub issues should be investigated:
- https://github.com/hilbert/hilbert-docker-images/issues/9
- http://www.flockport.com/run-gui-apps-in-lxc-containers/

**Comment by aptalca** [comment]
Based on what plex has done to get hardware acceleration to work, I believe ffmpeg in this image needs to be built with various hardware acceleration modules enabled (mainly vaapi and nvenc). Also for vaapi and quicksync, /dev/dri needs to be mapped as a device (and write permissions given to emby user).

I tried to build ffmpeg with nvenc in the container, but I know nothing about opensuse and thus failed.

**Comment by hurricanehrndz** [comment]
@aptalca,

Do you have any links or information on what exactly plex did?

**Comment by aptalca** [comment]
There is a very long forum thread on plex about transcoding and plenty of people got it to work in docker by mapping /dev/dri for intel and setting permissions: https://forums.plex.tv/discussion/250946/plex-media-server-hardware-transcoding-preview-3-1-6-0-3720#latest

I don't have details on what exactly they did with ffmpeg, but I know that they use their own custom built version (which I assume is built with the hardware encode options.

**Comment by aptalca** [comment]
Not sure if it is the latest, but just found this: https://forums.plex.tv/discussion/comment/1035133/#Comment_1035133

**Comment by hurricanehrndz** [comment]
@aptalca,

ffmpeg version included in the docker container is compiled with libva enabled, I will test with dri mapped and see what happens. That being said I'm sure it is the same thing with emby, as with plex, you need to map the right device and have the right permissions set.

**Comment by hurricanehrndz** [comment]
@aptalca ffmpeg static does not seem to support vaapi, the emby team will need to build their own ffmpeg that supports hardware decoding. This is on the list of things to get done.

**Comment by aptalca** [comment]
Just an update. I've been playing with docker and hardware transcoding and just got it to work with plex and an nvidia gt710 gpu.

The host is ubuntu 16, the container is based on linuxserver's plex image (ubuntu 16 based). 

I had to install the nvidia drivers inside the plex container as well, otherwise I kept getting "cuda not initialized" errors. Ran it with privileged mode so all devices are mapped. I also added the plex user to the "video" group in and out of the container (rather than changing permissions, which kept reverting back with each restart of the container).

**Comment by hurricanehrndz** [comment]
Thanks. Well aware. We are just working on our ffmpeg. Once that's complete
I'm sure we will be able to close this issue

**Comment by Dalto1** [comment]
Any updates?

**Comment by godfuture** [comment]
Also interested in updates :)

**Comment by godfuture** [comment]
What could be learned from the following article?
http://gernotklingler.com/blog/howto-get-hardware-accelerated-opengl-support-docker/
It says that the driver inside the container needs to be the same as from the host. And special rights (security issues not clarified) to execute X server from within the docker container.

Is this the same direction the emby container goes?

**Comment by LukePulverenti** [comment]
Closing this, as our docker container has VAAPI. Thanks.
