### ISSUE TITLE
Running this on NAS/Synology?

### ISSUE THREAD

**Issue by DracoMilesX** [MediaBrowser/Emby.Build#56]
Hello,

I tried to install this on my NAS because I wanted to limit the RAM usage which otherwise isn't possible.

But when trying to install it

docker run -it --rm -v /usr/local/bin:/target \
   emby/embyserver instl

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-conf-onetime: executing...
[cont-init.d] 01-conf-onetime: exited 0.
[cont-init.d] 02-user-onetime: executing...
[cont-init.d] 02-user-onetime: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Installing emby-server...
instl exited 0
grep: write error: Broken pipe
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

And when trying to run it with emby-server

/usr/local/bin/emby-server: line 14: getent: command not found
/usr/local/bin/emby-server: line 15: getent: command not found
Cleaning up stopped emby-server instances...
/usr/local/bin/emby-server: line 36: docker: command not found
Starting emby-server...
/usr/local/bin/emby-server: line 129: docker: command not found

Any assistance or a way to get it working on a Synology?

**Comment by LukePulverenti** [comment]
Hi, we have a dedicated package for Synology:

https://emby.media/nas-server.html

As a result, we are not really testing the Docker installation for it. Thanks.

**Comment by DracoMilesX** [comment]
Yeah thanks I noticed I originally came from the package but the package uses 1GB RAM on my NAS. That's why I wanted to try docker. Is there anyway to limit the usage with the package itself?

**Comment by hurricanehrndz** [comment]
Docker wrapper script is not designed for NAS devices. I would recommend you do a manual docker run command if possible.
