### ISSUE TITLE
Docker security - How to prevent access to root folders?

### ISSUE THREAD

**Issue by pthieu** [MediaBrowser/Emby.Build#60]
Went through the setup guide, got emby up and going on OMV 3.x, but looks like when I add a media library, it will allow me to search through everything from `/`:
![image](https://cloud.githubusercontent.com/assets/2908721/24394609/9d0421c2-136a-11e7-9f43-c7a03af69305.png)

```
root@omv:~# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:55:48 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:55:48 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

OS: Debian 8 (Jessie) -- `Linux omv 4.9.0-0.bpo.2-amd64 #1 SMP Debian 4.9.13-1~bpo8+1 (2017-02-27) x86_64 GNU/Linux`

Image:
```
root@omv:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
emby/embyserver     latest              5db093354d68        9 days ago          455 MB
```

systemd service script:
```
Description=Emby Media Server for emby
After=docker.service

[Service]
Type=simple
User=emby
ExecStart=/usr/local/bin/emby-server service
ExecStop=/usr/bin/docker stop -t 2 emby-server
ExecStopPost=/usr/bin/docker rm -f emby-server
Restart=on-abort
TimeoutSec=20

[Install]
WantedBy=multi-user.target
```

Read here (https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface) that containers aren't restricted in terms of folder permissions, but what I'm interpreting is that we map the guest directory to `/` for it to be able to have access. Noticed in the `systemd` file, we don't actually use `-v` to map volumes, but use the `${APP_CONFIG}/.emby-server/.emby-server.volumes` file. Not sure what's going on here but I'd like for emby to not see anything outside of the volumes I configure. Let me know if this is unrelated to this repo and I'll move issue.

**Comment by hurricanehrndz** [comment]
Not necessary since the root folder are the root of the containerize environment.
