### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by StarOrpheus** [MediaBrowser/Emby.Build#61]
Hi. I've pulled emby-server:armv7. When I'm trying to `curl 127.0.0.1:8096` on the machine with dockerd it says `connection refused`. In the emby-server console curl says me... nothing. No errors nor response data. What's wrong? 
OS - Armbian, 
Arch - armv7, 
PC - orange pi pc
 [logs here](https://gist.github.com/StarOrpheus/66fc41e1fab0be463315e539d7446c70) Strange error on the 91th line, but seems clear

**Comment by hurricanehrndz** [comment]
The latest build should be working, can you please try and let me know.

**Comment by hurricanehrndz** [comment]
No response.
