### ISSUE TITLE
Emby ARMv7 docker image

### ISSUE THREAD

**Issue by pablos91** [MediaBrowser/Emby.Build#62]
I'm sorry but you didn't updated armv7 build for the long time. Did you pass on this architecture ?? I can't connect to the server because it is Version 3.1.1.0 and no client would connect it (checked UWP, iOS, Android, Desktop Windows 10)

Please update docker image to Version 3.2.13.0 so i can manage to play any media file.

Thanks

**Comment by hurricanehrndz** [comment]
Will do. Thank you

**Comment by hurricanehrndz** [comment]
Image has been updated to latest stable.
