### ISSUE TITLE
Want to RUN as docker container, not install anything…?

### ISSUE THREAD

**Issue by hedefalk** [MediaBrowser/Emby.Build#63]
Sorry if this has been up before, but this:

`docker run -it --rm -v /usr/local/bin:/target emby/embyserver instl`

is really not something I want to do So I do not want to install anything on my file system, I want to RUN Emby in a container. There is no official image for that? Is this the one to use: https://github.com/dperson/emby

**Comment by aptalca** [comment]
It's in the read.me: https://github.com/MediaBrowser/Emby.Build#manual-run-and-installation

**Comment by hedefalk** [comment]
Thanks! Didn't see it.
