### ISSUE TITLE
.emby-server gets created in /home/root instead of /root

### ISSUE THREAD

**Issue by kugelzucker** [MediaBrowser/Emby.Build#64]
running the default commands given in the Readme.md on centos7, i get the .emby-server directory in /home/root .

unless there is some new policy that /root is off limits i think thats not on purpose.

**Comment by hurricanehrndz** [comment]
Thanks for the issue submission. This will be fix in the next major docker
update we do.

**Comment by LukePulverenti** [comment]
How will the change impact existing installs? Can they still function where they are?

**Comment by hurricanehrndz** [comment]
Yes, the update is only to address root home location. Either which way
individuals can specify the actual host directory they want use rather than
depending on the wrapper scripts automatic resolution.
