### ISSUE TITLE
restart.sh missing in container

### ISSUE THREAD

**Issue by devster31** [MediaBrowser/Emby.Build#65]
I recently downloaded the container, brand new, using `docker pull`, my current images are the ones below:
```
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
emby/embyserver      latest              b3b910425ef2        5 days ago          412.5 MB
emby/embyserver      x86_64              b3b910425ef2        5 days ago          412.5 MB
```
I installed it using a slightly modified command:
```sh
$ docker run -it --rm -v $HOME/bin:/target -e "APP_USER=$USER" emby/embyserver instl
```
and everything started fine using `EDGE=1 emby-server`. However after installing a plugin I tried restarting from the WebUI and nothing happened.
After closer inspection I noticed that `/usr/lib/emby-server/restart.sh` was missing inside the container, after downloading a copy from the repo `builders/emby-server/debfiles/restart.sh` everything seems to work.
Also `EMBY_PATH` seems to not be set in my container for some reason.

**Comment by hurricanehrndz** [comment]
Thanks for the feedback, I will have a look.

**Comment by aptalca** [comment]
Noticed this also. Because emby server is started with the option `restartpath` emby tries to automatically restart itself when a plugin is updated and crashes (or remains stuck in a down state to be more precise).

**Comment by hurricanehrndz** [comment]
Yup it is confirmed issue. I was going to fix on the next major update ("mono bump") but it seems to be some ways away, so I will try and get this done soon.
