### ISSUE TITLE
APP_USER breaks when APP_UID or APP_GID are certain values in docker container

### ISSUE THREAD

**Issue by joekrill** [MediaBrowser/Emby.Build#66]
## My Setup

I run Emby in a docker container manually on my system. I have a user on my host called `emby` (UID 997) that I typically run it under (with APP_UID), and a group called `media` (GID 996, using APP_GID):

```
docker create \
  --name emby \
  --restart always \
  -e APP_UID=`id -u emby` \
  -e APP_GID=`getent group media | cut -d: -f3` \
  -e TZ=America/New_York \
  -e VIRTUAL_HOST=my.external.hostname \
  -e VIRTUAL_PORT=8096 \
  -e LETSENCRYPT_HOST=my.external.hostname \
  -e LETSENCRYPT_EMAIL=me@example.com \
  -v /dev/rtc:/dev/rtc:ro \
  -v /srv/appdata/emby/config:/config \
  -v /srv/media:/media \
  emby/embyserver:latest
```

(The VIRTUAL_* and LETS_ENCRYPT_* environment variables aren't -- I don't think -- relevant here , but I'm including them for completeness.)

## The Error

I recently pulled the latest image and now when I startup my container I get this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-conf-onetime: executing...
[cont-init.d] 01-conf-onetime: exited 0.
[cont-init.d] 02-user-onetime: executing...
[cont-init.d] 02-user-onetime: exited 0.
[cont-init.d] 03-upgrade-onetime: executing...
[cont-init.d] 03-upgrade-onetime: exited 0.
[cont-init.d] 04-fix_dllmaps-onetime: executing...
[cont-init.d] 04-fix_dllmaps-onetime: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
groups: ‘appuser’: no such user
usermod: user 'appuser' does not exist
chown: invalid user: ‘appuser.appuser’
su: user appuser does not exist
groups: ‘appuser’: no such user
usermod: user 'appuser' does not exist
chown: invalid user: ‘appuser.appuser’
su: user appuser does not exist
groups: ‘appuser’: no such user
usermod: user 'appuser' does not exist
chown: invalid user: ‘appuser.appuser’
su: user appuser does not exist
<snip>
```

The last 4 lines then continue to be output in perpetuity, and the Emby server never starts.

## Additional Info

I've tried setting APP_USER=emby, in which case the 4 lines that repeat above change to these 2 lines:

```
chown: invalid user: ‘emby.emby’
su: user emby does not exist
``` 

Setting APP_USER=root works, but I really don't want to do that because that changes the permissions on my config directory (/srv/appdata/emby/config) to be owned by root.  

This all seems to have changed with the most recent image. I saw some discussion about a similar error someone was having [in the forums](https://emby.media/community/index.php?/topic/9754-docker/page-22#entry310378). He [seems to have fixed it](https://emby.media/community/index.php?/topic/9754-docker/page-23#entry311162) by removing `--net=host` -- which I'm not using in the first place.

## The Possible Culprit

I think that ultimately there is a problem with how the docker image is creating users and groups, and mapping the APP_UID and APP_GID to the container user and group names (APP_USER, EMBY_USER, etc). 

The output of `getent passwd` _within my docker container_ yields:

```
root:x:0:0:root:/root:/bin/bash
messagebus:x:499:499:User for D-Bus:/run/dbus:/bin/false
systemd-coredump:x:997:997:systemd Core Dumper:/:/sbin/nologin
systemd-network:x:996:996:systemd Network Management:/:/sbin/nologin
systemd-timesync:x:998:998:systemd Time Synchronization:/:/sbin/nologin
at:x:25:25:Batch jobs daemon:/var/spool/atjobs:/bin/bash
``` 

And in my particular case, my _host's_ `emby` user has a UID of 997. Which conflicts with `systemd-coredump` _inside the container_.

Further, the output of `getent group` within the container is:

```
root:x:0:
shadow:x:15:
dialout:x:16:
utmp:x:22:
users:x:100:
messagebus:x:499:
kmem:x:498:
lock:x:497:
tty:x:5:
audio:x:496:
cdrom:x:495:
disk:x:494:
input:x:493:
tape:x:492:
video:x:491:
systemd-journal:x:999:
systemd-coredump:x:997:
systemd-network:x:996:
systemd-timesync:x:998:
at:x:25:
appuser:x:1000:
emby:x:1001:
```

And my `media` user on my host has a GID of 996 -- which overlaps here with `systemd-network`.

So I'm guessing that ultimately when the [02-user-onetime](https://github.com/MediaBrowser/Emby.Build/blob/845edf4a668d975aad861657f7bad9f2bc880203/docker-containers/base/overlay-common/etc/cont-init.d/02-user-onetime) script is run and tries to create the user and group, it actually ends up creating them with an entirely different UID (note that `appuser` has a UID of 1000, not 997, which I believe is what it should have).

## Possibly solutions

1. [Workaround] I suppose that ultimately I could change the UID and GID for the user/group I want to run this under. But that's really just a bandaid in my case, and doesn't really seem ideal (plus I'll have to scour my entire system to make sure I've changed the appropriate file permissions). 

2. Get rid of reliance on `APP_USER`, or at least don't try to delete/create it in the container in the `02-user-onetime` script?  I'm not even sure this will work. But at least relying ONLY on `APP_UID` and `APP_GID` would ensure that the appropriate permissions are applied on the host system.

## Caveats

I may be totally misunderstanding how user/group mapping is happening between the host and docker containers. I know things have changed throughout dockers lifetime, as well. I also won't pretend I fully understand how the docker containers are working, so I might be totally missing something.

**Comment by hurricanehrndz** [comment]
Joe,

Thanks for the feedback. It seems the new docker image has been created
with additional systemd packages that created additional uid and gid. The
user creation scripts within the container will need to be adjusted in
order to resolve your issue. I won't be able to address this for two weeks.
Sorry for any inconveniences.

**Comment by lunatic1972** [comment]
If you are getting the endless error message of emby.emby user does not exist this is what I did to temporarily fix it.
1. sudo docker exec -it emby-server /bin/bash
2. zypper install nano
3. nano /etc/cont-init.d/02-user-onetime
4. add the following:
 if ! getent passwd emby > /dev/null; then
  useradd --system \
        --shell /bin/false \
        --no-create-home \
        --uid ${APP_GID} \
        --gid ${APP_GID} \
        --comment 'Emby server' emby > /dev/null 2>&1
fi
5. save the file (CTRL + O for nano), then CTRL+X (to exit out of nano)
6. Open another terminal (DO NOT EXIT from the docker machine yet)
7.  sudo docker commit emby-server
8.  sudo docker images (This will list the current images, latest one being first in list which you just created from the commit)
9.  Use the image name from step 8 to run a new instance of emby-server.  You may need to stop your previous container if its still running but not functioning (sudo docker stop emby-server) first
10. It should now be running as long as everything else was setup correctly

**Comment by lunatic1972** [comment]
One other thing, in my particular instance my uid ($APP_GID) and gid($APP_GID) were the same. Yours may vary and need to change the line to --uid $(APP_UID) and possibly the user emby
