### ISSUE TITLE
Environment variables for UID/GID no longer valid in Documentation

### ISSUE THREAD

**Issue by azmodude** [MediaBrowser/Emby.Build#69]
Hi,

I just noticed during my latest pull that the environment variables for running the Emby server under a specific `UID/GID` are no longer `APP_UID/APP_GID`, but seem to be `UID/GID` now (which works as designed as `s6-applyuidgid` is being called with the `-U` parameter). Documentation seems to be wrong on this or the change to `/etc/services.d/emby-server/run` was not intentional.

Interestingly enough my `/etc/services.d/emby-server/run` is completely different from what I can see in this repo - is this actually the place for the official Emby docker image or am I too dumb/blind to find the relevant `run` file?

Thanks!

**Comment by hurricanehrndz** [comment]
Nope it is not.

**Comment by azmodude** [comment]
It is not ... in regards to what point?

**Comment by hurricanehrndz** [comment]
This repo has nothing to do with the deployment or development of the Emby
container. The container is now using the .netcore binaries. If you have
questions regarding the development of the container it is best to post
your questions or issues on the Emby forums. I no longer donate any
considerable amount of time to this project. My apologies for not being
clear enough with my previous response. Best of luck.

**Comment by azmodude** [comment]
Ah, I see, thanks for clarification. Since the official image (I suppose emby/emby-server is still the official one?) on Docker Hub still links to this repository it is kind of misleading. Do you have any pointers on where the official image is being built/supported nowadays?

**Comment by hurricanehrndz** [comment]
Emby forums is the best source for all and any relevant info.

**Comment by LukePulverenti** [comment]
Our docker setup guide also lists everything that is supported:
https://docs.docker.com/installation/#installation
