### ISSUE TITLE
aarch64 image missing

### ISSUE THREAD

**Issue by andreipoe** [MediaBrowser/Emby.Build#71]
Hello,

A while ago I installed the aarch64 version of Emby Server, which I was able to download using:

```
docker pull emby/embyserver:aarch64
```

Trying to update the image today. the same command doesn't work any more, although the README of this repository still lists the `aarch64` tag. 

Has the naming changed, or am I missing something else?

Thanks.

**Comment by alucryd** [comment]
The old mono aarch64 images have been deprecated when we moved over to dotnet core. We are waiting on an official dotnet core aarch64 runtime to reinstate them. Apologies for the inconvenience.

**Comment by jonasfoe** [comment]
I am also waiting for the aarch64 image.

In the meantime I have tried adopting my old aarch64 mono configs with the arm32v7_neon docker image but it doesn't seem to work out.

Do you maybe have some information if the configs and databases are platform independent?
If I set up a new instance via the arm32v7_neon image on my arm64v8 machine, can I just seamlessly switch to the arm64v8 container later?

That information would be much appreciated as this loss of support has been quite unfortunate.
Thank you for your hard work though.

**Comment by alucryd** [comment]
Yes, the config and db directories are portable across all architectures.

**Comment by breneser** [comment]
Hi, wondering if there is any news on the images required ?

**Comment by alucryd** [comment]
aarch64 images are back on docker hub, now with dotnet core goodness.

**Comment by fbettag** [comment]
do you happen to have a link? i seem unable to find them.

**Comment by LukePulverenti** [comment]
Instructions can be found here for aarch64:
https://emby.media/docker-server.html
Please let us know if this helps. Thanks.

**Comment by fbettag** [comment]
thanks! i was looking for aarch64 not arm64 =)
