### ISSUE TITLE
If there are only BETA releases available on the release ATOM page docker fails to update and breaks the server

### ISSUE THREAD

**Issue by cdloh** [MediaBrowser/Emby.Build#72]
If the VERSION check doesn't find any stable versions it returns empty.

Then when it attempts to download a version it fails but proceeds to delete files under /usr/lib and is then unable to extract the ZIP file as it didn't download.

emby-server then cannot start and requires manual fixing.

**Comment by cdloh** [comment]
Something like this would work

`    URL=$(curl -I https://github.com/MediaBrowser/Emby/releases/latest | perl -n -e '/^Location: (.*)$/ && print "$1\n"')
    VERSION=$(basename $URL | tr -d '\r')`

**Comment by alucryd** [comment]
This repository has been deprecated ever since we switched over to netcore. Unfortunately I can't fin a way to unlink this repository on docker hub.

In any case, please update your docker image via a pull, this method is not supported anymore.

**Comment by kaeus** [comment]
I know this may not be supported, but is there any way to get that PR completed from @cdloh for those of us who may still rely on it for now? Every time emby hits enough beta releases, my docker container fails to create properly and I've had issues switching over.
