### ISSUE TITLE
ARMv7/armhf version missing 

### ISSUE THREAD

**Issue by lukemicallef** [MediaBrowser/Emby.Build#74]
Hi, I see that there is a standard ARMv7 install, but the :armv7 tag fails to pull anything through. Is this just a hangover from the mono to dot net switch?

**Comment by LukePulverenti** [comment]
Hi, we're not doing it as a tag anymore, it's a separate docker container:
https://hub.docker.com/u/emby/

Thanks.

**Comment by lukemicallef** [comment]
Thanks Luke. I tried searching and went through the docs, but didn't spot this.
