### ISSUE TITLE
Crash with version > 3.4.1.1

### ISSUE THREAD

**Issue by gsemet** [MediaBrowser/Emby.Build#75]
I cannot use a version of this docker image higher than 3.4.1.1, it does not start and fails with an error: 
```
Infinite recursion during resource lookup within System.Private.CoreLib
at System.Environment.FailFast(System.String)
...
at System.Globalization.CultureInfo.get_CompareInfo()
at System.StringComparer..cctor()
at System.AppDomain.Setup(System.Object)
```

v3.4.1.6 and higher does not work. Alse tested .11, .19.

v3.4.1.1 works.

**Comment by LukePulverenti** [comment]
What platform are you on?

**Comment by gsemet** [comment]
Hi.

Synology Docker (DS1815+). Worked great until update. :(

**Comment by adam111316** [comment]
Had this issue with Freenas / Rancher. Fixed by changing the env variable ICU_DATA /share/icu/61.1 (was previously set to icu/5...something)

**Comment by godfuture** [comment]
Are there any updates? I can't get the container working anymore...

**Comment by LukePulverenti** [comment]
Have you tried the latest version? Have you also tried our dedicated Synology package instead?

**Comment by LukePulverenti** [comment]
Were you overwriting the variable to begin with? Because the value you changed it to is actually our default value.

**Comment by godfuture** [comment]
Well, I started the container from a previous image. Therefore this value was not changed automatically. In general, I am not sure how variables are handled across different images...as the variable is part of the startup command...but this is another story I guess.

**Comment by LukePulverenti** [comment]
This is no longer an issue in newer versions. Thanks.
