### ISSUE TITLE
Can't update to latest releases even docker page shows changed entries

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/Emby.Build#76]
Hi folks, I tried to download the latest emby docker image, but docker says it hasn't changed. But when I look into the emby server tags section, there are new releases.
```
latest: Pulling from emby/embyserver
Digest: sha256:70e41c6cc03f20d0d6be33fc5af220b33dac79dc621fd6710273aea37e5af146
Status: Image is up to date for emby/embyserver:latest
```
My current image is 19d old. But on the docker hub, the latest is 1d old.
```
Tag Name | Compressed Size | Last Updated
latest | 85 MB | a day ago
beta | 89 MB | a day ago
3.4.1.24 | 89 MB | a day ago
```
Why does docker keep telling me that there are no updates?

**Comment by alucryd** [comment]
Our build system pushes every image that hasn't been purged every time a new tag is pushed. Docker realizes the image has already been pushed thanks to its hash, but docker hub still bumps the update date even though the image hasn't actually changed. This is kinda stupid but nothing we can do about it.
