### ISSUE TITLE
Unable to upgrade docker to the latest version

### ISSUE THREAD

**Issue by groenator** [MediaBrowser/Emby.Build#77]
When I run emby-server update command from the container or using the docker exec command, I get this error:

`docker exec -it emby-server update emby-server
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"update\": executable file not found in $PATH": unknown`

I run the docker pull image, as it is showing below, the image was pulled it the latest tag.

`docker pull emby/embyserver
Using default tag: latest
latest: Pulling from emby/embyserver
Digest: sha256:689dce03e8f16aa0510b7511c6dd611d203b2971ff105e77929e5d5910f35a2f
Status: Image is up to date for emby/embyserver:latest`

I want to upgrade my server to the latest version of Emby, which is `3.5.2.0`. Was this version pushed to docker latest tag?

**Comment by alucryd** [comment]
This method is not supported anymore. Please upgrade using docker pull instead.

**Comment by groenator** [comment]
Hi,

I manage to upgrade the server via docker pull. Thanks for your help.
