### ISSUE TITLE
TZ timezone not used

### ISSUE THREAD

**Issue by pcm2a** [MediaBrowser/Emby.Build#79]
I am on 4.1.0.10 beta running in docker on a Synology NAS. I have the environment property set TZ = America/Chicago. When I connect to the container I can do "echo $TZ" and see that it is set. My timezone is still set to UTC.

Is it possible that the docker image is not including the tzdata package?

**Comment by alucryd** [comment]
Our docker image does contain tzdata. What makes you say it's not used?

**Comment by pcm2a** [comment]
I create a new container from the image, I have updated to the latest 4.1.0.13. In the container I am only changing two things, the UID to my userid and adding TZ = "America/Chicago". I start up the container and connect to it.

This is from the docker container that should be set to CST but is on UTC:
```
/ # echo $TZ
America/Chicago
/ # date
Sat Mar  9 16:18:23 UTC 2019
/ # cat /etc/localtime
TZif2UTCTZif2�UTC
UTC0
```
This is from the Synology host system:
```
/ # exit
:~$ date
Sat Mar  9 10:19:37 CST 2019
```

**Comment by alucryd** [comment]
This date binary is from busybox, for some reason it respects /etc/localtime, not TZ. But it doesn't matter anyway, emby is built on glibc and should respect TZ.

**Comment by pcm2a** [comment]
What I was experiencing was incorrect embyserver.txt timestamps (in UTC) and scheduled jobs kicking off in UTC time. The live tv guide displayed CST even without the TZ change. However, I have made so many changes to docker trying to fix this that the logs are currently running in the right timezone. I will close this until I come up with some better reproducible steps.
