### ISSUE TITLE
DNS search domain

### ISSUE THREAD

**Issue by Axachi** [MediaBrowser/Emby.Build#80]
Running on docker ubuntu. everything works fine, but I wanted to migrate from old windows  emby. But now I need to enter ipaddress? andyway to get it to read hostname with my serchdomain from host? 

Eg_ mediaserver instead of mediaserver.domain.com

**Comment by LukePulverenti** [comment]
Hi, what do you mean by "now I need to enter ipaddress"? Where exactly are you referring to?

**Comment by Axachi** [comment]
Sorry i found it out. I was thinking uncle path.. hehe Microsoft head doing linux config.. I mapped the folder on the host. Now it works.

Sent from Nine<http://www.9folders.com/>
________________________________
Fra: Luke <notifications@github.com>
Sendt: søndag 10. mars 2019 22:30
Til: MediaBrowser/Emby.Build
Kopi: Stian Hill; Author
Emne: Re: [MediaBrowser/Emby.Build] DNS search domain (#80)


Hi, what do you mean by "now I need to enter ipaddress"? Where exactly are you referring to?
