### ISSUE TITLE
Scan All Libraries not work for me

### ISSUE THREAD

**Issue by ayuLiao** [MediaBrowser/Emby.Build#81]
I use ubuntu 14.04 install docker, then use docker run the embyserver.

I use root to install docker and also use root run embyserver.  This is my command:

```
(root)# docker run --name emby -d \
-v /data1/embyserver/config:/config \
-v /data1/embyserver/share:/mnt/share \
-p 8096:8096 \
-p 8920:8920 \
--env UID=0 \
--env GID=0 \
--env GIDLIST=0 \
emby/embyserver:latest
```

Embyserver is run for me but when I use Scan All Libraries, I can't get anything in embyserver.

![image](https://user-images.githubusercontent.com/19529872/58559465-c4f91500-8255-11e9-948f-770cf794fcaf.png)

**Comment by LukePulverenti** [comment]
Hi there, is this still an issue?

**Comment by ayuLiao** [comment]
This problem has existed until I give up use Emby.
