### ISSUE TITLE
ffmpeg link out of date

### ISSUE THREAD

**Issue by AciDCooL** [MediaBrowser/Emby.Build#82]
old link: 
https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
new link:
https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

**Comment by LukePulverenti** [comment]
Hi, we don't use that anymore, and haven't for quite a long time. Our packages embed ffmpeg. Please let us know if this helps. Thanks.
