### ISSUE TITLE
Time and timezone are incorrect

### ISSUE THREAD

**Issue by juergen-venne** [MediaBrowser/Emby.Build#83]
using the emby server in docker on raspberry pi 4
The output of 'date' on my raspi which is correct is:
date
Fr 16. Aug 12:35:42 CEST 2019
The output of in date inside the container is (docker exec -it emby /bin/sh):
date
Fri Aug 16 10:35:45 UTC 2019

I did not pass any arguments -e regarding timezone to the docker run command.
How to sync that?

**Comment by LukePulverenti** [comment]
Hi, you'll need to specify the timezone when using the Docker run command. Please let us know if this helps. Thanks.

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen if you're still having an issue. Thanks.
