### ISSUE TITLE
synology ds918+ can't use hardware acceleration

### ISSUE THREAD

**Issue by SuperNG6** [MediaBrowser/Emby.Build#84]
Hello, I have emby premiere,My device is synology ds918+,I can't use hardware acceleration.the synology not have `getent` command,I use `cat /etc/group` command,not find It's about the video result,I hope you can tell me what I should do,thank you very much.

````
sudo docker create \
    --name=emby \
    --device /dev/dri:/dev/dri \
    --env UID=1026 \
    --env GID=100 \
    emby/embyserver:latest
````
````
ls -l /dev/dri/
total 0
crw------- 1 root root 226,   0 Jan 10 20:27 card0
crw------- 1 root root 226,  64 Jan 10 20:27 controlD64
crw------- 1 root root 226, 128 Jan 10 20:27 renderD128
````

**Comment by LukePulverenti** [comment]
Hi there, please attach an ffmpeg log example, as well as the emby server hardware detection log. thanks.

**Comment by SuperNG6** [comment]
> Hi there, please attach an ffmpeg log example, as well as the emby server hardware detection log. thanks.

I think it should be a permission issue, if I use chmod 777 /dev/dri,emby can hardware acceleration

**Comment by LukePulverenti** [comment]
Thanks for the feedback.
