### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by dokbua** [MediaBrowser/Emby.Build#87]
What is the procedure for moving a emby container from one host to another?   If I just copy my docker folder and start it, I am prompted to set everything up from scratch on the home page.

**Comment by LukePulverenti** [comment]
Hi, you would just do a docker pull. If you do this again with the latest, that should give you 4.4.3. Please let us know if this helps. Thanks.

**Comment by NDNELSON** [comment]
I am still the same behavior, how can I fix?

**Comment by LukePulverenti** [comment]
> I am still the same behavior, how can I fix?

What exactly have you done?
